Fix ValueError for missing story rating.
Traceback (most recent call last):
  File "play.py", line 292, in <module>
    play_aidungeon_2()
  File "play.py", line 158, in play_aidungeon_2
    rating_float = float(rating)
ValueError: could not convert string to float: